### ISSUE TITLE
At far zoom levels, small properties can be hard to see

### ISSUE THREAD

**Issue by hampelm** [alexbhill/project-pip#16]
If an owner only has a couple properties, it can be hard to see them when you're zoomed far out. 

![screen shot 2016-05-09 at 12 40 55 pm](https://cloud.githubusercontent.com/assets/86435/15120363/6435e34c-15e3-11e6-9e7c-1c6b605b0171.png)

One solution would be to apply a thick border style to properties at far zoom levels when an owner is selected (maybe only for owners with <50 properties?).

Eg 

```
[zoom <= 13] {
  line-width: 5;
}
```

**Comment by ughitsaaron** [comment]
Thanks a bajillion, @hampelm!

**Comment by alexbhill** [comment]
@hampelm Thoughts on converting to point locations at smaller zoom level?

**Comment by hampelm** [comment]
Points might be perfect @alexbhill. I didn't know how to do it but found this tutorial using multiple layers on cartodb -- smart!: http://gis.stackexchange.com/questions/167486/can-i-use-cartocss-to-have-a-polygon-change-shape-or-symbol-upon-different-zoom

**Comment by ughitsaaron** [comment]
Oh, interesting–might be able to look into that for a future long-term solution. For now, line-width does the trick.
