### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by daniwilson** [alexbhill/project-pip#18]
I live at 15311 Glastonbury and the owner information is incorrect. Sean Vandenbrink owns the property (and adjacent lot), but your map indicates that a Loretta Abrams is the owner. I was really excited when I saw your map as it could be a really useful tool for neighbors who are trying to get a handle on blight (in addition to resources like Motor City Mapping), but this mistake could make things confusing for folks who are trying to get in touch with property owners. 

Where did you find your records and information? 

Thank you in advance for answering my question.

**Comment by daniwilson** [comment]
I also just noticed you sourced your information from the city. I checked their portal and it also lists Sean as the correct owner. Not sure where the slip occurred.

**Comment by ughitsaaron** [comment]
The current data reflects records released from the city last year at the beginning of 2015. We're in the process of processing data released at the beginning of this year. If this was a recent purchase, that might explain where the slip up occurred. I forwarded this along to my colleagues on the project to verify the issue. Thanks for bringing this up!

**Comment by jmakers** [comment]
Hi - Thanks for drawing this to our attention and for checking out and responding to the site. 

I am working on an update now utilizing the city's 2016 data. It shows Sean Vanderbrink as the owner. It will be caught in the update. As for the city's 2015 data, it's a strange mix of multiple years. The 2016 data is much cleaner and I think we will all find it more useful.

**Comment by daniwilson** [comment]
Thanks for your quick response, Aaron! The purchase was made in 2012.

On Wed, Jun 8, 2016 at 1:28 PM, Aaron Petcoff notifications@github.com
wrote:

> Hi @daniwilson https://github.com/daniwilson. The current data reflects
> records released from the city last year at the beginning of 2015. We're in
> the process of processing data released at the beginning of this year. If
> this was a recent purchase, that might explain where the slip up occurred.
> I forwarded this along to my colleagues on the project to verify the issue
> and correct it ASAP. Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/alexbhill/project-pip/issues/18#issuecomment-224666722,
> or mute the thread
> https://github.com/notifications/unsubscribe/AS571kcGPVAmWv99ncIlf94hPmhkKmFOks5qJvvUgaJpZM4IxMQD
> .

## 

_Danielle Wilson_
616.902.4429 | danielleruthwilson@gmail.com
